spring:
  profiles:
    active: secret

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

kakao:
  key: ${kakaokey}

odsay: 
  key: ${odsaykey}

map:
  key: ${mapkey}


server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
